steps:
  - bash: |
      echo ______________Agent Variables______________
      echo BuildDirectory: $(Agent.BuildDirectory)
      echo ContainerMapping: $(Agent.ContainerMapping)
      echo HomeDirectory: $(Agent.HomeDirectory)
      echo ID: $(Agent.Id)
      echo JobName: $(Agent.JobName)
      echo JobStatus: $(Agent.JobStatus)
      echo MachineName: $(Agent.MachineName)
      echo Name: $(Agent.Name)
      echo OS: $(Agent.OS)
      echo OSArchitecture: $(Agent.OSArchitecture)
      echo TempDirectory: $(Agent.TempDirectory)
      echo ToolsDirectory: $(Agent.ToolsDirectory)
      echo WorkFolder: $(Agent.WorkFolder)

      echo ______________Build Variables______________
      echo ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)
      echo BuildId: $(Build.BuildId)
      echo BuildNumber: $(Build.BuildNumber)
      echo BuildUri: $(Build.BuildUri)
      echo BinariesDirectory: $(Build.BinariesDirectory)
      echo ContainerId: $(Build.ContainerId)
      echo DefinitionName: $(Build.DefinitionName)
      echo DefinitionVersion: $(Build.DefinitionVersion)
      echo QueuedBy: $(Build.QueuedBy)
      echo QueuedById: $(Build.QueuedById)
      echo Reason: $(Build.Reason)
      echo Repository.Clean: $(Build.Repository.Clean)
      echo Repository.LocalPath:$(Build.Repository.LocalPath)
      echo Repository.ID: $(Build.Repository.ID)
      echo Repository.Name: $(Build.Repository.Name)
      echo Repository.Provider: $(Build.Repository.Provider)
      echo Repository.Tfvc.Workspace: $(Build.Repository.Tfvc.Workspace)
      echo Repository.Uri: $(Build.Repository.Uri)
      echo RequestedFor: $(Build.RequestedFor)
      echo RequestedForEmail: $(Build.RequestedForEmail)
      echo RequestedForId: $(Build.RequestedForId)
      echo SourceBranch: $(Build.SourceBranch)
      echo SourceBranchName: $(Build.SourceBranchName)
      echo SourcesDirectory: $(Build.SourcesDirectory)
      echo SourceVersion: $(Build.SourceVersion)
      echo SourceVersionMessage: $(Build.SourceVersionMessage)
      echo StagingDirectory: $(Build.StagingDirectory)
      echo Repository.Git.SubmoduleCheckout: $(Build.Repository.Git.SubmoduleCheckout)
      # Unavailable during feature branch build
      echo SourceTfvcShelveset: $(Build.SourceTfvcShelveset)
      echo TriggeredBy.BuildId: $(Build.TriggeredBy.BuildId)
      echo TriggeredBy.DefinitionId: $(Build.TriggeredBy.DefinitionId)
      echo TriggeredBy.DefinitionName: $(Build.TriggeredBy.DefinitionName)
      echo TriggeredBy.BuildNumber: $(Build.TriggeredBy.BuildNumber)
      echo TriggeredBy.ProjectID: $(Build.TriggeredBy.ProjectID)
      
      echo ______________Environment Variables______________
      echo Name: $(Environment.Name)
      echo Id: $(Environment.Id)
      echo ResourceName: $(Environment.ResourceName)
      echo ResourceId: $(Environment.ResourceId)

      echo ______________System Variables______________
      echo AccessToken: $(System.AccessToken)
      echo CollectionId: $(System.CollectionId)
      echo CollectionUri: $(System.CollectionUri)
      echo DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
      echo DefinitionId: $(System.DefinitionId)
      echo HostType: $(System.HostType)
      echo JobAttempt: $(System.JobAttempt)
      echo JobDisplayName: $(System.JobDisplayName)
      echo JobId: $(System.JobId)
      echo JobName: $(System.JobName)
      echo PhaseAttempt: $(System.PhaseAttempt)
      echo PhaseDisplayName: $(System.PhaseDisplayName)
      echo PhaseName: $(System.PhaseName)
      echo StageAttempt: $(System.StageAttempt)
      echo StageDisplayName: $(System.StageDisplayName)
      echo StageName: $(System.StageName)
      echo PullRequest.IsFork: $(System.PullRequest.IsFork)

      echo ______________ Unavailable during feature branch build______________
      echo PullRequest.PullRequestId: $(System.PullRequest.PullRequestId)
      echo PullRequest.PullRequestNumber: $(System.PullRequest.PullRequestNumber)
      echo PullRequest.SourceBranch: $(System.PullRequest.SourceBranch)
      echo PullRequest.SourceRepositoryURI: $(System.PullRequest.SourceRepositoryURI)
      echo PullRequest.TargetBranch: $(System.PullRequest.TargetBranch)

      echo TeamFoundationCollectionUri: $(System.TeamFoundationCollectionUri)
      echo TeamProject: $(System.TeamProject)
      echo TeamProjectId: $(System.TeamProjectId)
    displayName: variables & values
    